# (name, address, size, signed, note)
REGISTERS = [
    ('Return Delay Time',      9,   1, False, 'x2 usec'),
    ('Drive Mode',             10,  1, False, 'bit2: time-based profile'),
    ('Operating Mode',         11,  1, False, ''),
    ('Homing Offset',          20,  4, True,  'ticks'),
    ('Temperature Limit',      31,  1, False, 'deg C'),
    ('Max Voltage Limit',      32,  2, False, 'x0.1 V'),
    ('Min Voltage Limit',      34,  2, False, 'x0.1 V'),
    ('PWM Limit',              36,  2, False, ''),
    ('Current Limit',          38,  2, False, 'model ticks'),
    ('Velocity Limit',         44,  4, False, ''),
    ('Max Position Limit',     48,  4, False, 'ticks'),
    ('Min Position Limit',     52,  4, False, 'ticks'),
    ('Shutdown',               63,  1, False, 'error-bit mask'),
    ('Torque Enable',          64,  1, False, '0/1'),
    ('LED',                    65,  1, False, '0/1'),
    ('Hardware Error Status',  70,  1, False, 'bitfield'),
    ('Velocity I Gain',        76,  2, False, ''),
    ('Velocity P Gain',        78,  2, False, ''),
    ('Position D Gain',        80,  2, False, ''),
    ('Position I Gain',        82,  2, False, ''),
    ('Position P Gain',        84,  2, False, ''),
    ('Feedforward 2nd Gain',   88,  2, False, 'acceleration'),
    ('Feedforward 1st Gain',   90,  2, False, 'velocity'),
    ('Bus Watchdog',           98,  1, False, ''),
    ('Goal PWM',               100, 2, True,  ''),
    ('Goal Current',           102, 2, True,  ''),
    ('Goal Velocity',          104, 4, True,  ''),
    ('Profile Acceleration',   108, 4, False, 'ms or deg/s^2'),
    ('Profile Velocity',       112, 4, False, 'ms or deg/s'),
    ('Goal Position',          116, 4, True,  'ticks'),
    ('Moving',                 122, 1, False, '0/1'),
    ('Moving Status',          123, 1, False, 'bitfield'),
    ('Present PWM',            124, 2, True,  ''),
    ('Present Current/Load',   126, 2, True,  'Load on XL430, Current on XL330'),
    ('Present Velocity',       128, 4, True,  ''),
    ('Present Position',       132, 4, True,  'ticks'),
    ('Velocity Trajectory',    136, 4, True,  ''),
    ('Position Trajectory',    140, 4, True,  'ticks'),
    ('Present Input Voltage',  144, 2, False, 'x0.1 V'),
    ('Present Temperature',    146, 1, False, 'deg C'),
]

# Friendly aliases for `write <name>` so callers do not need raw addresses.
BY_NAME = {
    'torque': (64, 1),
    'led': (65, 1),
    'operating_mode': (11, 1),
    'drive_mode': (10, 1),
    'profile_velocity': (112, 4),
    'profile_acceleration': (108, 4),
    'goal_current': (102, 2),
    'current_limit': (38, 2),
    'homing_offset': (20, 4),
    'position_p_gain': (84, 2),
    'position_i_gain': (82, 2),
    'position_d_gain': (80, 2),
}
