// Generated by tools/gen_model.py -- do not edit.
#pragma once

namespace gripper_servo
{

constexpr int kJoints = 8;
constexpr int kLinks = 9;
constexpr int kCapsuleCount = 9;

/// Joint order everywhere in gripper_servo, and the interface names
/// the controller claims. Motor 1..8.
inline constexpr const char * kJointNames[kJoints] = {
  "C_2_Joint", "C_3_Joint", "A_2_Joint", "A_3_Joint", "B_2_Joint", "B_3_Joint", "A_1_Joint", "B_1_Joint"};

// Link i+1 is driven by joint i; link 0 is the palm.
struct JointModel
{
  int parent;         ///< parent link index
  float origin[12];   ///< row-major 3x4, parent frame -> joint frame
  float axis[3];
  float lower;        ///< rad
  float upper;
};

struct CapsuleModel
{
  int link;
  float a[3];         ///< segment start, link frame, metres
  float b[3];         ///< segment end
  float radius;       ///< already shrunk, see SHRINK above
};

inline constexpr JointModel kJointModel[kJoints] = {
  {0, {-3.4332051e-06f, -3.44320464e-06f, -1.0f, -0.0145001631f, -1.0f, 1.34295906e-07f, 3.43320464e-06f, 0.0383998353f, 1.34284085e-07f, 1.0f, -3.4432051e-06f, 0.0770002598f}, {0.0f, 0.0f, 1.0f}, -0.221657f, 1.26013f},   // motor 1  C_2_Joint
  {1, {1.0f, 5.5339034e-07f, -8.07151498e-07f, 6.31723492e-07f, -5.53390475e-07f, 1.0f, -1.67176704e-07f, 0.0499998496f, 8.07151405e-07f, 1.67177151e-07f, 1.0f, -0.0261002724f}, {0.0f, 0.0f, 1.0f}, -2.0944f, 0.644027f},   // motor 2  C_3_Joint
  {7, {-0.999876626f, 0.015707725f, 6.9235907e-06f, -0.0384004039f, -6.87274177e-06f, 3.29117356e-06f, -1.0f, -0.0290008044f, -0.015707725f, -0.999876626f, -3.18281238e-06f, -0.0390000457f}, {0.0f, 0.0f, -1.0f}, -0.499164f, 1.23744f},   // motor 3  A_2_Joint
  {3, {1.0f, -2.4249211e-07f, -1.42958947e-07f, 1.36339317e-07f, 2.4249211e-07f, 1.0f, -1.58888812e-09f, 0.0499997474f, 1.42958947e-07f, 1.58885345e-09f, 1.0f, -0.00589972461f}, {0.0f, 0.0f, -1.0f}, -2.0944f, 0.644027f},   // motor 4  A_3_Joint
  {8, {-1.0f, 7.41320574e-08f, 7.50359004e-06f, 0.0384001953f, -7.50358979e-06f, 3.27320566e-06f, -1.0f, -0.0289001111f, -7.41566182e-08f, -1.0f, -3.2732051e-06f, -0.0389995578f}, {0.0f, 0.0f, 1.0f}, -0.499164f, 1.23744f},   // motor 5  B_2_Joint
  {5, {1.0f, 3.51844564e-07f, 3.20096403e-07f, -1.93065522e-08f, -3.51844561e-07f, 1.0f, -8.37649595e-09f, 0.0499995561f, -3.20096406e-07f, 8.37638333e-09f, 1.0f, -0.0057995579f}, {0.0f, 0.0f, 1.0f}, -2.0944f, 0.644027f},   // motor 6  B_3_Joint
  {0, {-0.999609914f, -0.0279288515f, 4.15304639e-08f, 0.0295000587f, -0.0279288515f, 0.999609914f, -7.22524837e-06f, 1.39331777e-07f, 1.60278625e-07f, -7.22358979e-06f, -1.0f, 0.0380002526f}, {0.0f, 0.0f, 1.0f}, -1.5708f, 1.5708f},   // motor 7  A_1_Joint
  {0, {-1.0f, -7.51359229e-06f, -3.55061713e-07f, -0.0294996344f, -7.51358979e-06f, 1.0f, -7.02359246e-06f, -6.91998508e-07f, 3.55114485e-07f, -7.02358979e-06f, -1.0f, 0.0380001102f}, {0.0f, 0.0f, 1.0f}, -1.5708f, 1.5708f},   // motor 8  B_1_Joint
};

/// Links in an order where every parent precedes its children.
inline constexpr int kFkOrder[kLinks] = {0, 1, 2, 7, 8, 3, 4, 5, 6};

inline constexpr CapsuleModel kCapsules[kCapsuleCount] = {
  {2, {0.00354549787f, 0.0508467974f, 0.0130328384f}, {0.00188891112f, 0.0303337178f, 0.0112363679f}, 0.00649390879f},   // C_3_Link_001
  {2, {0.00188510689f, 0.0302866111f, 0.0112322424f}, {0.000230288646f, 0.00979543046f, 0.00943768976f}, 0.0121513441f},   // C_3_Link_001
  {2, {0.000228805246f, 0.0097770619f, 0.0094360811f}, {-0.00142853887f, -0.010745396f, 0.00763878926f}, 0.0128211838f},   // C_3_Link_001
  {4, {-0.00222475488f, 0.0507320678f, -0.012481889f}, {-0.00123644525f, 0.0302069383f, -0.0109737062f}, 0.00636821332f},   // A_3_Link
  {4, {-0.0012341791f, 0.0301598751f, -0.010970248f}, {-0.000248461399f, 0.00968857451f, -0.00946602045f}, 0.0122647716f},   // A_3_Link
  {4, {-0.000245103354f, 0.00961883493f, -0.009460896f}, {0.000742455046f, -0.0108906931f, -0.00795385954f}, 0.0127338599f},   // A_3_Link
  {6, {0.00365704496f, 0.0508471539f, -0.0102274773f}, {0.00196914012f, 0.0303481412f, -0.0120196491f}, 0.00638512594f},   // B_3_Link
  {6, {0.00196518485f, 0.0303001059f, -0.0120238487f}, {0.000275013244f, 0.00977356408f, -0.0138184272f}, 0.0122336402f},   // B_3_Link
  {6, {0.000273795273f, 0.00975877225f, -0.0138197204f}, {-0.00141715768f, -0.0107772587f, -0.0156151286f}, 0.0128180044f},   // B_3_Link
};

/// Symmetric; false where the links share a joint and always touch.
inline constexpr bool kMonitored[kLinks][kLinks] = {
  {false, false, false, false, false, false, false, false, false},   // base_link
  {false, false, false, false, false, false, false, false, false},   // C_2_Link
  {false, false, false, false, true , false, true , false, false},   // C_3_Link_001
  {false, false, false, false, false, false, false, false, false},   // A_2_Link
  {false, false, true , false, false, false, true , false, false},   // A_3_Link
  {false, false, false, false, false, false, false, false, false},   // B_2_Link
  {false, false, true , false, true , false, false, false, false},   // B_3_Link
  {false, false, false, false, false, false, false, false, false},   // A_1_Link
  {false, false, false, false, false, false, false, false, false},   // B_1_Link_001
};

}  // namespace gripper_servo
