# Generated by tools/gen_reach.py -- do not edit.
"""How far the hand can close, in a straight line, at each spread angle.

Closing further needs the spread joints to move on the way, which during a
grasp sweeps the object out of the hand. Staying inside this table means
gripper_servo never has to veto anything: a BLOCKED status becomes a sign
that something bypassed the table, not routine behaviour.
"""

# Flexion joint lower limits, in the message joint order. Zero is fully
# open and these are the fully curled end, so a closure fraction scales
# them. Taken from the URDF so nothing has to copy them by hand.
FLEXION_LOWER = [-0.2217, -2.0944, -0.4992, -2.0944, -0.4992, -2.0944]

# degrees, and the safe closure fraction, already backed off 0.03
# from the measured edge.
REACH_TABLE = [
    (-90.0, 0.960),
    (-85.0, 0.960),
    (-80.0, 0.960),
    (-75.0, 0.960),
    (-70.0, 0.960),
    (-65.0, 0.960),
    (-60.0, 0.960),
    (-55.0, 0.960),
    (-50.0, 0.960),
    (-45.0, 0.960),
    (-40.0, 0.960),
    (-35.0, 0.960),
    (-30.0, 0.960),
    (-25.0, 0.960),
    (-20.0, 0.510),
    (-15.0, 0.440),
    (-10.0, 0.410),
    (-5.0, 0.390),
    (+0.0, 0.370),
    (+5.0, 0.350),
    (+10.0, 0.340),
    (+15.0, 0.330),
    (+20.0, 0.320),
    (+25.0, 0.310),
    (+30.0, 0.300),
    (+35.0, 0.290),
    (+40.0, 0.290),
    (+45.0, 0.280),
    (+50.0, 0.280),
    (+55.0, 0.280),
    (+60.0, 0.280),
    (+65.0, 0.290),
    (+70.0, 0.290),
    (+75.0, 0.290),
    (+80.0, 0.290),
    (+85.0, 0.300),
    (+90.0, 0.300),
]


def max_closure(spread_degrees):
    """Safe closure fraction for a spread angle.

    Takes the smaller of the two bracketing samples rather than
    interpolating. The limit has a cliff in it -- around -20 degrees it
    drops from 96% to 51% -- and interpolating across that would hand back
    a value the hand cannot actually reach.
    """
    if spread_degrees <= REACH_TABLE[0][0]:
        return REACH_TABLE[0][1]
    if spread_degrees >= REACH_TABLE[-1][0]:
        return REACH_TABLE[-1][1]
    for (a, va), (b, vb) in zip(REACH_TABLE, REACH_TABLE[1:]):
        if a <= spread_degrees <= b:
            return min(va, vb)
    return 0.0
