#!/usr/bin/env python3
"""Generate the table of how far the hand can close at each spread angle.

Self-collision cuts the closure space in two. The far half is reachable only by
moving the spread joints on the way, which during a grasp would sweep the object
out of the hand -- and it is not worth reaching anyway, because curling that far
takes the fingertips past each other instead of together. So instead of planning
around the obstacle, this bakes its edge into a table the decision layer can stay
inside by construction.

    python3 tools/gen_reach.py

Writes src/gripper_grasp/gripper_grasp/reach_table.py.
"""

import os
import sys

import numpy as np
import trimesh

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_model import cover                                   # noqa: E402
from selfcollision import PKG, fk, load                       # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, 'src', 'gripper_grasp', 'gripper_grasp', 'reach_table.py')

DISTAL = ['A_3_Link', 'B_3_Link', 'C_3_Link_001']
# Joint vector order, motor 1..8, matching gripper_msgs/GripperGoal.
NAMES = ['C_2_Joint', 'C_3_Joint', 'A_2_Joint', 'A_3_Joint',
         'B_2_Joint', 'B_3_Joint', 'A_1_Joint', 'B_1_Joint']
FLEXION_LINKS = ['C_2_Link', 'C_3_Link_001', 'A_2_Link', 'A_3_Link',
                 'B_2_Link', 'B_3_Link']

SPREAD_STEP = 5.0          # degrees
CLOSURE_STEP = 0.01
MARGIN = 0.03              # back off the edge, the model is not exact


def segment_distance(p1, q1, p2, q2):
    d1, d2, r = q1 - p1, q2 - p2, p1 - p2
    a, e, f = d1 @ d1, d2 @ d2, d2 @ r
    if a <= 1e-12 and e <= 1e-12:
        return float(np.linalg.norm(r))
    c = d1 @ r
    b = d1 @ d2
    denom = a * e - b * b
    s = float(np.clip((b * f - c * e) / denom, 0, 1)) if denom > 1e-12 else 0.0
    t = (b * s + f) / e if e > 1e-12 else 0.0
    if t < 0:
        t, s = 0.0, float(np.clip(-c / a, 0, 1))
    elif t > 1:
        t, s = 1.0, float(np.clip((b - c) / a, 0, 1))
    return float(np.linalg.norm(r + s * d1 - t * d2))


def main():
    joints = load()
    capsules = {l: cover(trimesh.load(f'{PKG}/meshes/{l}.stl', process=False), 3)
                for l in DISTAL}
    lower = [joints[l]['lower'] for l in FLEXION_LINKS]

    def feasible(closure, spread):
        q = dict(zip(NAMES, [closure * v for v in lower] + [spread, -spread]))
        placed = {}
        for l in DISTAL:
            T = fk(joints, l, q)
            placed[l] = [((T @ np.append(a, 1))[:3], (T @ np.append(b, 1))[:3], r)
                         for a, b, r in capsules[l]]
        for i, a in enumerate(DISTAL):
            for b in DISTAL[i + 1:]:
                for p1, q1, r1 in placed[a]:
                    for p2, q2, r2 in placed[b]:
                        if segment_distance(p1, q1, p2, q2) < r1 + r2:
                            return False
        return True

    degrees = np.arange(-90.0, 90.0 + SPREAD_STEP / 2, SPREAD_STEP)
    rows = []
    print(f'  {"spread":>8}{"max closure":>13}')
    for deg in degrees:
        spread = np.deg2rad(deg)
        reached = 0.0
        step = CLOSURE_STEP
        while reached + step <= 1.0 and feasible(reached + step, spread):
            reached += step
        safe = max(reached - MARGIN, 0.0)
        rows.append((float(deg), round(safe, 3)))
        print(f'  {deg:+7.0f}°{safe * 100:12.0f}%')

    lines = [
        '# Generated by tools/gen_reach.py -- do not edit.',
        '"""How far the hand can close, in a straight line, at each spread angle.',
        '',
        'Closing further needs the spread joints to move on the way, which during a',
        'grasp sweeps the object out of the hand. Staying inside this table means',
        'gripper_servo never has to veto anything: a BLOCKED status becomes a sign',
        'that something bypassed the table, not routine behaviour.',
        '"""',
        '',
        '# Flexion joint lower limits, in the message joint order. Zero is fully',
        '# open and these are the fully curled end, so a closure fraction scales',
        '# them. Taken from the URDF so nothing has to copy them by hand.',
        'FLEXION_LOWER = [' + ', '.join(f'{v:.4f}' for v in lower) + ']',
        '',
        f'# degrees, and the safe closure fraction, already backed off {MARGIN:.2f}',
        '# from the measured edge.',
        'REACH_TABLE = [',
    ]
    lines += [f'    ({deg:+.1f}, {safe:.3f}),' for deg, safe in rows]
    lines += [
        ']',
        '',
        '',
        'def max_closure(spread_degrees):',
        '    """Safe closure fraction for a spread angle.',
        '',
        '    Takes the smaller of the two bracketing samples rather than',
        '    interpolating. The limit has a cliff in it -- around -20 degrees it',
        '    drops from 96% to 51% -- and interpolating across that would hand back',
        '    a value the hand cannot actually reach.',
        '    """',
        '    if spread_degrees <= REACH_TABLE[0][0]:',
        '        return REACH_TABLE[0][1]',
        '    if spread_degrees >= REACH_TABLE[-1][0]:',
        '        return REACH_TABLE[-1][1]',
        '    for (a, va), (b, vb) in zip(REACH_TABLE, REACH_TABLE[1:]):',
        '        if a <= spread_degrees <= b:',
        '            return min(va, vb)',
        '    return 0.0',
        '',
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write('\n'.join(lines))
    print(f'\n  wrote {OUT}')


if __name__ == '__main__':
    main()
